### ISSUE TITLE
influxdb-spring 6.10.0 does not work with spring boot 3.2.0

### ISSUE THREAD

**Issue by yikuo123** [influxdata/influxdb-client-java#649]
it throws exception:

```
Caused by: java.lang.NoSuchMethodError: org.springframework.boot.actuate.autoconfigure.health.CompositeHealthContributorConfiguration: method 'void <init>()' not found
	at com.influxdb.spring.health.InfluxDB2HealthIndicatorAutoConfiguration.<init>(InfluxDB2HealthIndicatorAutoConfiguration.java:50) ~[influxdb-spring-6.10.0.jar:6.10.0]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:197) ~[spring-beans-6.1.1.jar:6.1.1]
```

**Comment by powersj** [comment]
@bednar in the past, what versions of spring boot have we supported? From the [readme](https://github.com/influxdata/influxdb-client-java/tree/master/spring#spring-boot-compatibility) I see comments about some compatibility, but nothing about major or minor versions.

**Comment by bednar** [comment]
The current version of the client is dependent on Spring Boot `2.7.17`. We can prepare an upgrade to version 3.x, which will be a major release for the client, because it will be breaking change.

**Comment by bachmann-ubique** [comment]
Is there a timeline for the version 3.x, that fixes this Issue?

**Comment by bednar** [comment]
@bachmann-ubique, this issue is at the top of our backlog for the v2 client maintenance. I am hopeful that it will be resolved in the next maintenance release scheduled for the end of this month.
